name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on:
  workflow_dispatch:
    push:
    branches:
      - master

env:
  INTERNAL_NAME: EmoteLog
  RELEASE_NAME: NoxEmoteLog
  CONFIGURATION: Release
  PERSONAL_PLUGIN_REPO: Maxunit/MyDalamudPlugins
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
    - name: Restore
      run: dotnet restore -r win
    - name: Build
      run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: PluginRepoZip
        path: ${{ env.INTERNAL_NAME }}/bin/x64//${{ env.CONFIGURATION }}/${{ env.RELEASE_NAME }}
        if-no-files-found: error
        retention-days: 14
    - name: Tag
      run: |
        git tag -am "[Automated build $BUILD_VERSION]" "$TAG_NAME"
        git push origin "$TAG_NAME"
      shell: bash
      env:
        BUILD_VERSION: ${{ needs.precheck.outputs.buildVersion }}
        TAG_NAME: ${{ needs.precheck.outputs.tagName }}
        GIT_AUTHOR_NAME: GitHub Action
        GIT_COMMITTER_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master
        repository: ${{ env.PERSONAL_PLUGIN_REPO }}
        token: ${{ secrets.PAT }}
    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: PluginRepoZip
        path: plugins/${{ env.INTERNAL_NAME }}
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        add: plugins/
        pathspec_error_handling: exitImmediately
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update ${{ env.INTERNAL_NAME }}
